services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    image: haittdocker/portfolio:${IMAGE_TAG:-latest}
    container_name: ${CONTAINER_NAME:-portfolio}
    ports:
      - "${PORT:-8080}:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=8080
    labels:
      - "com.docker.compose.project=${PROJECT_NAME:-portfolio}" 