version: '3.8'

services:
  portfolio:
    build: .
    image: haittdocker/portfolio:v0
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=8080 