name: Deploy to beta user on VPS

on:
    push:
        branches: ["beta"]

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-24.04
        steps:
            - name: Deploy on VPS via SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST_BETA }}
                  username: ${{ secrets.USER_BETA }}
                  key: ${{ secrets.KEY_BETA }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE_BETA }}
                  port: ${{ secrets.PORT_BETA }}
                  script: |
                      cd ~/portfolio
                      git fetch --all
                      git reset --hard origin/beta
                      git pull origin beta
                      echo "${{secrets.ENV_BETA}}" > .env
                      docker compose build --no-cache
                      docker compose down
                      docker compose up -d portfolio
