name: Deploy to prod user on VPS

on:
    push:
        branches: ["main"]

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-24.04
        steps:
            - name: Deploy on VPS via SSH
              uses: appleboy/ssh-action@v0.1.6
              with:
                  host: ${{ secrets.HOST_PROD }}
                  username: ${{ secrets.USER_PROD }}
                  key: ${{ secrets.KEY_PROD }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE_PROD }}
                  port: ${{ secrets.PORT_PROD }}
                  script: |
                      cd ~/portfolio
                      git fetch --all
                      git reset --hard origin/main
                      git pull origin main
                      echo "${{secrets.ENV_PROD}}" > .env
                      
                      # Set environment variables
                      export CONTAINER_NAME=portfolio-prod
                      export PORT=8080
                      export IMAGE_TAG=prod
                      export PROJECT_NAME=portfolio-prod
                      export COMPOSE_PROJECT_NAME=portfolio-prod
                      
                      # Stop and remove only production container
                      docker compose -p portfolio-prod down || true
                      
                      # Clean up any orphaned containers/images
                      docker rm -f portfolio-prod || true
                      docker rmi haittdocker/portfolio:prod || true
                      
                      # Build and start the new container with project name
                      docker compose -p portfolio-prod build --no-cache
                      docker compose -p portfolio-prod up -d portfolio
                      
                      # Verify the container is running
                      docker compose -p portfolio-prod ps
