name: Deploy to beta user on VPS

on:
    push:
        branches: ["beta"]

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-24.04
        steps:
            - name: Deploy on VPS via SSH
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.HOST_BETA }}
                  username: ${{ secrets.USER_BETA }}
                  key: ${{ secrets.KEY_BETA }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE_BETA }}
                  port: ${{ secrets.PORT_BETA }}
                  script: |
                      cd ~/portfolio
                      git fetch --all
                      git reset --hard origin/beta
                      git pull origin beta
                      echo "${{secrets.ENV_BETA}}" > .env

                      # Stop and remove existing containers
                      docker compose down || true

                      # Remove any stopped containers and unused images
                      docker system prune -f

                      # Check if port 8081 is in use and kill the process if needed
                      sudo lsof -ti:8081 | xargs -r sudo kill -9
                      
                      # Set environment variables for docker-compose
                      export PORT=8081
                      export CONTAINER_NAME=portfolio-beta

                      # Build and start the new container
                      docker compose build --no-cache
                      docker compose up -d portfolio
                      
                      # Verify the container is running
                      docker compose ps
